apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: bioconductor/bioc-redis:manager
      imagePullPolicy: Always
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 1
      volumeMounts:
        - name: azure
          mountPath: /mnt/azure
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
#      command: ["Rscript"]
#      args: ["-e", "BiocKubeInstall::kube_run('3.13', image_name = 'bioc_docker', worker_pool_size=6L)"]
  restartPolicy: "OnFailure"
  volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      shareName: biocbinaries
      readOnly: false
