apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: release
  labels:
    app: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio  
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
        - name: manager
          image: bioconductor/bioc-redis:az-manager
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1.1Gi
              cpu: 1
          volumeMounts:
            - name: azure
              mountPath: /host/
          env:
            - name: PASSWORD
              value: "bioc"
          ports:
            - containerPort: 8787
#          command: ["Rscript"]
#          args: ["-e", "BiocKubeInstall::kube_run('3.12', image_name = 'bioconductor_docker', worker_pool_size=60L)"]
      volumes:
        - name: azure
          azureFile:
            secretName: azure-secret
            shareName: biocbinaries
            readOnly: false
