apiVersion: apps/v1
kind: Deployment
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: 10
  selector:
    matchLabels:
      tier: workcluster
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: bioconductor/bioc-redis:RELEASE_3_12
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1Gi
            cpu: 700m
          limits:
            memory: 4Gi
            cpu: 1.2
        volumeMounts:
         - name: azure
           mountPath: /host/
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: biocbinaries
          readOnly: false
