apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: {{ .Values.managerImage }}:{{ .Values.managerImageTag }}
      imagePullPolicy: {{ .Values.pullPolicy }}
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 1700m
      volumeMounts:
        - name: {{ .Values.volumeMountName }}
          mountPath: {{ .Values.volumeMountPath }}
      env:
        - name: PASSWORD
          value: {{ .Values.rstudioPassword | quote }}
      ports:
        - containerPort: 8787
      command: ["Rscript"]
      args: ["-e", "BiocKubeInstall::kube_run('{{ .Values.biocVersion }}', image_name = '{{ .Values.dockerImageName }}', workers = {{ .Values.workerPoolSize }})"]
  restartPolicy: {{ .Values.restartPolicy | quote}}
  volumes:
    - name: {{ .Values.volumeName }}
      hostPath:
        path: {{ .Values.volumeHostPath }} 
#  volumes:
#  - name: {{ .Values.volumeMountName }}
#    persistentVolumeClaim:
#      claimName: local-provision
