# Default values for k8s-redis-bioc-chart. This is a YAML-formatted
# file. Declare variables to be passed into your templates.

#
# user-oriented configuration
#
# clusterNamespace: release
workerPoolSize: 50              # Number of workers in the cluster
## TODO: this has to change
dockerImageName: 'anvil-jupyter'  # Image name for which binaries are created
biocVersion: '3.14'
workerImageTag: RELEASE_3_14    # Needs to match the biocVersion

# Manager image
managerImage: bioconductor/bioc-redis
managerImageTag: manager

# Worker image
workerImage: bioconductor/bioc-redis-jupyter


# Volume mount
volumeMountName: bioc-nfs-mount
volumeMountPath: /host
volumeMountSize: 200Gi

# service key name
serviceKey: bioc-binaries.json
#
# internal settings
#

# This value is set to 0 so that both manager and worker pods enter the image as 'root'
uid: 0

# image management (manager, worker, redis)
pullPolicy: Always
restartPolicy: OnFailure

# internal redis-specific config
redis:
  redisImage: redis
  redisImageTag: '5.0'
  containerPort: 6379
