ARG RELEASE=RELEASE_3_20
FROM bioconductor/bioconductor_docker:$RELEASE

# Never want these containers to use the binary repo,
# since the point is to build from source for the binary repo
ENV BIOCONDUCTOR_USE_CONTAINER_REPOSITORY=FALSE

RUN apt-get update && \
        apt-get install -y --no-install-recommends libhiredis-dev && \
        rm -rf /var/lib/apt/lists/*

RUN R -e 'if(strsplit(BiocManager::install("Bioconductor/BiocParallel", dependencies = TRUE), "/")[[1]][2] %in% rownames(installed.packages())) q(status = 0) else q(status = 1)'
RUN R -e 'if(strsplit(BiocManager::install("Bioconductor/BiocKubeInstall", dependencies = TRUE), "/")[[1]][2] %in% rownames(installed.packages())) q(status = 0) else q(status = 1)'

COPY worker.R /home/docker/
