FROM bioconductor/bioconductor_docker:RELEASE_3_20

RUN apt-get update && \
        apt-get install -y --no-install-recommends libhiredis-dev && \
        rm -rf /var/lib/apt/lists/*

COPY BiocRprofile /home/rstudio/.Rprofile
COPY worker.R /home/docker/

RUN R -e 'BiocManager::install("Bioconductor/AnVILGCP")'

WORKDIR BiocKubeInstall

RUN git clone https://github.com/Bioconductor/BiocKubeInstall.git . && \
    git checkout -b local-host origin/local-host && \
    R -e 'remotes::install_local(".", repos = BiocManager::repositories())'

