FROM bioconductor/bioconductor_docker:devel

RUN apt-get update && \
	apt-get install -y --no-install-recommends libhiredis-dev vim && \
	rm -rf /var/lib/apt/lists/*

COPY manager_demo.R /home/rstudio/manager_demo.R
COPY 01-Renviron /etc/cont-init.d/01-Renviron
COPY BiocRprofile /home/rstudio/.Rprofile

RUN R -e 'BiocManager::install("Bioconductor/AnVILGCP")'
RUN R -e 'BiocManager::install("Bioconductor/BiocParallel")'

WORKDIR BiocKubeInstall

RUN git clone https://github.com/Bioconductor/BiocKubeInstall.git . && \
    git checkout tags/local-host && \
    R -e 'remotes::install_local(".", repos = BiocManager::repositories())'

