apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: jupyter
spec:
  securityContext:
    runAsUser: {{ .Values.uid }}
  containers:
    - name: manager
      image: {{ .Values.managerImage }}:{{ .Values.managerImageTag }}
      imagePullPolicy: {{ .Values.pullPolicy }}
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 1700m
      volumeMounts:
        - name: {{ .Values.volumeMountName }}
          mountPath: {{ .Values.volumeMountPath }}
        - name: service-key
          mountPath: /home/key.json
          subPath: {{ .Values.serviceKey }}
      command: ["Rscript"]
      args: ["-e", "BiocKubeInstall::kube_run('{{ .Values.biocVersion }}', image_name = '{{ .Values.dockerImageName }}', workers = {{ .Values.workerPoolSize }})"]
  restartPolicy: {{ .Values.restartPolicy | quote}}
  volumes:
  - name: {{ .Values.volumeMountName }}
    persistentVolumeClaim:
      claimName: nfs
  - name: service-key
    secret:
      secretName: bioc-binaries-service-account-auth
      items:
        - key: service_account_key
          path: {{ .Values.serviceKey }}
