apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-provisioning-demo
  labels:
    demo: nfs-pv-provisioning
spec:
  storageClassName: sc-pd-delete
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.volumeMountSize }}
