apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: bioconductor/bioc-redis:manager
      imagePullPolicy: Always
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 1
      volumeMounts:
        - name: bioc-nfs-mount
          mountPath: /host
#        - name: service-key
#          mountPath: /home/rstudio/key.json
#          subPath: {{ .Values.serviceKey }}
      env:
        - name: PASSWORD
          value: bioc
      ports:
        - containerPort: 8787
      command: ["Rscript"]
      args: ["-e", "BiocKubeInstall::kube_run('3.13', image_name = 'bioconductor_docker', workers = 4)"]
  restartPolicy: OnFailure
  volumes:
  - name: bioc-nfs-mount
    persistentVolumeClaim:
      claimName: nfs
#  - name: service-key
#    secret:
#      secretName: bioc-binaries-service-account-auth
#      items:
#        - key: service_account_key
#          path: {{ .Values.serviceKey }}
