apiVersion: v1
appVersion: "1.0"
description:  Kubernetes application to build Bioconductor package binaries using the bioconductor_docker images on GKE.
name: k8s-redis-bioc-chart
version: 3.14.0
maintainers:
  - name: Nitesh Turaga
  - name: Alex Mahmoud
  - name: Martin Morgan
dependencies:
  - name: nfs-server-provisioner
    repository: https://raw.githubusercontent.com/almahmoud/nfs-ganesha-server-and-external-provisioner/gh-pages/
    version: 1.5.0
    condition: nfs.deploy
    alias: nfs
    tags:
      - nfs