# Default values for k8s-redis-bioc-chart. This is a YAML-formatted
# file. Declare variables to be passed into your templates.

#
# user-oriented configuration
#
# clusterNamespace: release
workerPoolSize: 50              # Number of workers in the cluster
dockerImageName: 'bioconductor_docker'  # Image name for which binaries are created
biocVersion: '3.14'
workerImageTag: RELEASE_3_14    # Needs to match the biocVersion

# Manager image
managerImage: bioconductor/bioc-redis
managerImageTag: manager

# Worker image
workerImage: bioconductor/bioc-redis

# Volume mount
volumeMountName: bioc-nfs-mount
volumeMountPath: /host
volumeMountSize: 200Gi

# GCP Pesristent Disk name
gcpPdName: "manual-pd"

# service key name
serviceKey: bioc-binaries.json

# RStudio access
rstudioPassword: bioc         # RStudio password on manager

#
# internal settings
#

# image management (manager, worker, redis)
pullPolicy: Always
restartPolicy: OnFailure

# internal RStudio-specific config
rstudio:
  port: 8787                    # RStudioServer configured to listen here
  protocol: http
  type: NodePort

# internal redis-specific config
redis:
  redisImage: redis
  redisImageTag: '5.0'
  containerPort: 6379
