# Source: k8s-redis-bioc-chart/templates/redis-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  containers:
    - name: master
      image: redis:5.0
      imagePullPolicy: Always
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
  restartPolicy: OnFailure
