# Source: k8s-redis-bioc-chart/templates/worker-replicaset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: 8
  selector:
    matchLabels:
      tier: workcluster
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: bioconductor/bioc-redis:RELEASE_3_14
        imagePullPolicy: Always
        resources:
          requests:
            memory: "800Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
         - mountPath: /host
           name: bioc-nfs-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: bioc-nfs-mount
        persistentVolumeClaim:
          claimName: nfs
