apiVersion: v1
kind: Service
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  type: {{ .Values.rstudio.type }} ## LoadBalanacer
  ports:
    - port: 80
      targetPort: {{ .Values.rstudio.protocol }}
      protocol: TCP
      name: {{ .Values.rstudio.protocol }}
  selector:
    app: rstudio
