apiVersion: apps/v1
kind: Deployment
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: {{ .Values.workerPoolSize }}
  selector:
    matchLabels:
      tier: workcluster
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: {{ .Values.biocImage }}:{{ .Values.biocImageTag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
          requests:
            memory: 1Gi
            cpu: 700m
          limits:
            memory: 2Gi
            cpu: 1
        volumeMounts:
         - name: {{ .Values.volumeMountName }}
           mountPath: {{ .Values.volumeMountPath }}
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: {{ .Values.volumeMountName}}
        persistentVolumeClaim:
          claimName: nfs
