apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: mr148/bioc-redis:manager
      imagePullPolicy: Always
      resources:
        requests:
          memory: "500Mi"
          cpu: 500m
        limits:
          memory: 1Gi
          cpu: 1
      volumeMounts:
        - name: local-provision
          mountPath: /host
      env:
        - name: PASSWORD
          value: bioc
      ports:
        - containerPort: 8787
      command: ["Rscript"]
#      args: ["-e", "sessionInfo()"]
      args: ["-e", "BiocKubeInstall::kube_run('3.14', image_name = '/host', workers = 20, dry.run = FALSE, depth = TRUE)"]
  restartPolicy: OnFailure
  volumes:
    - name: local-provision
      persistentVolumeClaim:
        claimName: local-pvc-name
