apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}
      imagePullPolicy: {{ .Values.pullPolicy }}
      resources:
        {{- toYaml .Values.manager.resources | nindent 8 }}
      volumeMounts:
        - name: nfs-data
          mountPath: {{ .Values.persistence.mountPath }}
        - name: service-key
          mountPath: /home/key.json
          subPath: {{ .Values.serviceKey }}
      env:
        - name: PASSWORD
          value: {{ .Values.rstudioPassword | quote }}
      ports:
        - containerPort: 8787
      command: ["sh"]
      args:
        - -c
        - {{ if .Values.manager.extraCommand -}}
          {{- tpl .Values.manager.extraCommand $ }};
          {{- end -}}
          {{ .Values.manager.defaultCommand }}
  restartPolicy: {{ .Values.restartPolicy | quote}}
  volumes:
  - name: nfs-data
    persistentVolumeClaim:
      claimName: {{.Release.Namespace}}-nfs
  - name: service-key
    secret:
      secretName: bioc-binaries-service-account-auth
      items:
        - key: service_account_key
          path: {{ .Values.serviceKey }}
