apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: {{ .Values.managerImage }}:{{ .Values.managerImageTag }}
      imagePullPolicy: {{ .Values.pullPolicy }}
      resources:
        requests:
          memory: 250Mi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1700m
      volumeMounts:
        - name: {{ .Values.volumeMountName }}
          mountPath: {{ .Values.volumeMountPath }}
        - name: service-key
          mountPath: /home/key.json
          subPath: {{ .Values.serviceKey }}
      env:
        - name: PASSWORD
          value: {{ .Values.rstudioPassword | quote }}
      ports:
        - containerPort: 8787
      command: ["sh"]
      args:
        - -c
        - {{ if .Values.extraManagerCommands -}}
          {{- tpl .Values.extraManagerCommands $ }};
          {{- end -}}
          Rscript -e 'BiocKubeInstall::kube_run("{{ .Values.biocVersion }}", image_name = "{{ .Values.dockerImageName }}", workers = {{ .Values.workerPoolSize }})'
  restartPolicy: {{ .Values.restartPolicy | quote}}
  volumes:
  - name: {{ .Values.volumeMountName }}
    persistentVolumeClaim:
      claimName: {{.Release.Namespace}}-nfs
  - name: service-key
    secret:
      secretName: bioc-binaries-service-account-auth
      items:
        - key: service_account_key
          path: {{ .Values.serviceKey }}
