apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Namespace}}-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "{{ .Values.persistence.storageClass }}"
  resources:
    requests:
      storage: {{.Values.persistence.size}}