apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-provisioning-demo
  labels:
    demo: nfs-pvc-provisioning
spec:
  storageClassName: manual
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.volumeMountSize }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace}}-nfs-pv-provisioning-demo
  labels:
    demo: nfs-pv-provisioning
spec:
  storageClassName: manual
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: {{ .Values.volumeMountSize }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: nfs-pvc-provisioning-demo
  gcePersistentDisk:
    pdName: {{ .Values.gcpPdName }}
    fsType: ext4
---
