apiVersion: apps/v1
kind: Deployment
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: {{ .Values.workerPoolSize }}
  selector:
    matchLabels:
      tier: workcluster
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: {{ .Values.workerImage }}:{{ .Values.workerImageTag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1500m
        volumeMounts:
         - mountPath: {{ .Values.volumeMountPath }}
           name: {{ .Values.volumeMountName }}
        command: ["sh"]
        args:
        - -c
        - {{ if .Values.extraWorkerCommands -}}
          {{- tpl .Values.extraWorkerCommands $ }};
          {{- end -}}
          R -f /home/docker/worker.R
      volumes:
      - name: {{ .Values.volumeMountName }}
        persistentVolumeClaim:
          claimName: {{.Release.Namespace}}-nfs
