apiVersion: apps/v1
kind: Deployment
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: {{ .Values.workerPoolSize }}
  selector:
    matchLabels:
      tier: workcluster
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: {{ .Values.workerImage }}:{{ .Values.workerImageTag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
          limits:
            memory: 1500Mi
            cpu: 800m
        volumeMounts:
         - mountPath: {{ .Values.volumeMountPath }}
           name: {{ .Values.volumeMountName }}
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: {{ .Values.volumeMountName }}
        persistentVolumeClaim:
          claimName: {{.Release.Namespace}}-nfs
