apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  hostPath:
    path: /media/mr148/1D24A0EA4286043C/kubedisks
