apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: 60Gi
  hostPath:
    path: /home/mramos/data/minikube
