apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: bioconductor/bioc-redis:manager
      imagePullPolicy: Always
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "750m"
      volumeMounts:
        - name: local-volume
          mountPath: /host
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
#      command: ["Rscript"]
#      args: ["-e", "BiocKubeInstall::kube_run('3.13', image_name = 'bioconductor_docker', workers = 3)"]
  restartPolicy: "OnFailure"
  volumes:
  - name: local-volume
    hostPath:
      path: /Users/nitesh/R/bioconductor_docker/data/
      type: DirectoryOrCreate
      
