apiVersion: v1
appVersion: "1.0"
description: Kubernetes application to build Bioconductor package binaries using the bioconductor_docker images on AKS
name: k8s-redis-bioc-chart
version: 3.12.0
maintainers:
  - name: Nitesh Turaga