name: docker build manager and release

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push manager
        id: docker_build_manager
        uses: docker/build-push-action@v2
        with:
          file: inst/docker/Dockerfile.manager
          context: ./inst/docker
          push: true
          tags: bioconductor/bioc-redis:manager
      
      - name: Build and push release
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          file: inst/docker/Dockerfile.worker.RELEASE_3_14
          context: ./inst/docker
          push: true
          tags: bioconductor/bioc-redis:RELEASE_3_14

      - name: Build and push devel
        id: docker_build_devel
        uses: docker/build-push-action@v2
        with:
          file: inst/docker/Dockerfile.worker.RELEASE_3_15
          context: ./inst/docker
          push: true
          tags: bioconductor/bioc-redis:RELEASE_3_15

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
