name: Delete k8s cluster

## Cluster is shut down at 1pm on Monday, Wed, Fri
## The k8s cluster has 3 hours to do the job
on:
  schedule:
    - cron:  '* 13 * * 1,3,5'
 
env:
  GKE_CLUSTER: biock8sredis
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: binaryBuilder

jobs:
  setup-start-deploy:
    name: Delete GKE cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Delete cluster
    - run: |-
        gcloud container clusters delete "$GKE_CLUSTER" --zone "$GKE_ZONE"
        
