name: start k8s cluster and deploy binary build

## Cluster starts at 12pm on Tuesday, Thursday and Saturday
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'

env:
  GKE_CLUSTER: biock8sredis
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: binaryBuilder

jobs:
  setup-start-deploy:
    name: Setup, start, Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Start cluster
    - run: |-
        gcloud container clusters create \
          --zone "$GKE_ZONE" \
          --num-nodes 10 \
          --machine-type=e2-standard-4 "$GKE_CLUSTER"

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
       gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Create secret for cluster
      run: |-
        echo "$GKE_SA_KEY" > bioc-binaries.json && \
        kubectl create secret generic bioc-binaries-service-account-auth \
          --from-file=service_account_key=bioc-binaries.json
      shell: bash
      env:
        GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}

    - name: Check secret 
      run: |-
        kubectl describe secrets/bioc-binaries-service-account-auth

    - name: Deploy bioc release helm chart
      run: |
        helm install biock8sredis --set workerPoolSize=50 \
          --set biocVersion='3.13' \
          --set clusterNamespace='release' \
          --set workerImageTag='RELEASE_3_13' inst/helm-chart --wait

    - name: check
      run: |
        kubectl get all
