name: release - start k8s cluster and deploy binary build

## Cluster starts at 12pm on Tuesday, Thursday and Saturday
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * 4'

env:
  GKE_CLUSTER: biock8sredis
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: binaryBuilder
  GCP_PD_SIZE: 200Gi

jobs:
  setup-start-deploy:
    name: Setup, start, Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set prefix with date
      id: prefix
      run: echo "::set-output name=prefix::$(echo $(date +'%m-%d-%H-%M-%S'))"

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Start cluster
    - run: |-
        gcloud container clusters create \
          --zone "$GKE_ZONE" \
          --num-nodes 10 \
          --machine-type=e2-standard-4 "$GKE_CLUSTER"

    - name: Create GCP Disk
      run: gcloud compute disks create "biockubeinstall-nfs-pd-${{ steps.prefix.outputs.prefix }}" --size $GCP_PD_SIZE --zone "$GKE_ZONE"

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
       gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Create secret for cluster
      run: |-
        echo "$GKE_SA_KEY" > bioc-binaries.json && \
        kubectl create secret generic bioc-binaries-service-account-auth \
          --from-file=service_account_key=bioc-binaries.json
      shell: bash
      env:
        GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}

    - name: Check secret 
      run: |-
        kubectl describe secrets/bioc-binaries-service-account-auth

    - name: Deploy bioc release helm chart
      run: |
        helm install biock8sredis --set workerPoolSize=50 \
          --set biocVersion='3.14' \
          --set workerImageTag='RELEASE_3_14' \
          --set volumeMountSize=$GCP_PD_SIZE \
          --set gcpPdName="biockubeinstall-nfs-pd-${{ steps.prefix.outputs.prefix }}" inst/helm-chart --wait

    - name: check
      run: |
        kubectl get all
