name: Start GKE cluster and build devel then release

## Cluster starts at 12pm on Tuesday, Thursday and Saturday
on: 
  workflow_dispatch:
    inputs:
      major_ver:
        description: 'Major release to run'
        required: true
        default: '3'
      minor_ver:
        description: 'Minor release to run'
        required: true
        default: '15'

env:
  CLUSTER_BASE_NAME: biock8sredis
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: binaryBuilder
  NFS_PD_SIZE: 100Gi
  NODE_DISK_SIZE: 30Gi
  NAMESPACE: devel
  NODE_TYPE: e2-standard-4

jobs:
  clusterlaunch:
    name: Start GKE cluster
    runs-on: ubuntu-latest
    outputs:
      prefix: ${{ steps.prefix.outputs.prefix }}
    steps:
    - name: Set prefix with date
      id: prefix
      run: echo "::set-output name=prefix::$(echo $(date +'%m-%d-%H-%M-%S'))"

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Start cluster
    - run: |-
        gcloud container clusters create \
          --zone "$GKE_ZONE" \
          --num-nodes 10 \
          --disk-size="$NODE_DISK_SIZE" \
          --machine-type="$NODE_TYPE" "$CLUSTER_BASE_NAME-${{ steps.prefix.outputs.prefix }}"

  deploychart:
    name: Deploy helm chart and wait
    runs-on: ubuntu-latest
    needs: clusterlaunch
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Create GCP Disk
      run: gcloud compute disks create "biockubeinstall-nfs-pd-${{needs.clusterlaunch.outputs.prefix}}" --size $NFS_PD_SIZE --zone "$GKE_ZONE"

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
       gcloud container clusters get-credentials "$CLUSTER_BASE_NAME-${{needs.clusterlaunch.outputs.prefix}}" --zone "$GKE_ZONE"

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Create secret for namespace
      run: |-
        echo "$GKE_SA_KEY" > bioc-binaries.json && \
        kubectl create namespace $NAMESPACE && \
        kubectl create secret generic -n $NAMESPACE bioc-binaries-service-account-auth \
          --from-file=service_account_key=bioc-binaries.json
      shell: bash
      env:
        GKE_SA_KEY: ${{secrets.GKE_SA_KEY}}

    - name: Deploy helm chart
      run: |
        helm install biock8sredis -n $NAMESPACE --set workers.poolSize=50 \
          --timeout 600s \
          --set biocVersion="${{ github.event.inputs.major_ver }}.${{ github.event.inputs.minor_ver }}" \
          --set workers.image.tag="RELEASE_${{ github.event.inputs.major_ver }}_${{ github.event.inputs.minor_ver }}" \
          --set persistence.size=$NFS_PD_SIZE \
          --set persistence.gcpPdName="biockubeinstall-nfs-pd-${{needs.clusterlaunch.outputs.prefix}}" inst/helm-chart --wait

    - name: check
      run: |
        kubectl -n $NAMESPACE get all

    # Requires kubectl client version > 1.23
    - name: Get logs and events
      run: sh -c "while true; do kubectl -n $NAMESPACE logs manager > /tmp/logs && echo 'Tail of logs:' && tail /tmp/logs && echo 'GREP of errors:' && grep -i 'error' /tmp/logs && sleep 5; done" & kubectl -n $NAMESPACE  wait --for=jsonpath='{.status.phase}'=Succeeded --timeout=36000s pod/manager
      continue-on-error: true

    - name: Helm delete the release
      run: helm delete biock8sredis -n $NAMESPACE
      continue-on-error: true

    # Delete pd
    - run: gcloud compute disks delete --zone "$GKE_ZONE" --quiet $(gcloud compute disks list --format="value(name)" --filter='status~READY' --filter='name~biockubeinstall-nfs-pd-${{needs.clusterlaunch.outputs.prefix}}')
      continue-on-error: true

  cleanup:
    name: Cleanup GKE cluster
    if: always()
    needs: [clusterlaunch,deploychart]
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Set kubeconfig
    - run: gcloud container clusters get-credentials "$CLUSTER_BASE_NAME-${{needs.clusterlaunch.outputs.prefix}}" --zone "$GKE_ZONE"
      continue-on-error: true

    # Delete cluster
    - run: gcloud container clusters delete "$CLUSTER_BASE_NAME-${{needs.clusterlaunch.outputs.prefix}}" --zone "$GKE_ZONE" --quiet
      continue-on-error: true

    # Delete  pd
    - run: gcloud compute disks delete --zone "$GKE_ZONE" --quiet $(gcloud compute disks list --format="value(name)" --filter='status~READY' --filter='name~biockubeinstall-nfs-pd-${{needs.clusterlaunch.outputs.prefix}}')
      continue-on-error: true
